parameters:
    mon_parametre: ma_valeur

services:
#    oc_plateforme.example:
#        class: OC\PlateformeBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    oc_platform.antispam:
        class: OC\PlateformeBundle\Antispam\OCAntispam
        arguments:
            - "@mailer"
            - %locale%
            - 50